### ISSUE TITLE
file format for BBO has changed over time

### ISSUE THREAD

**Issue by rdhyee** [BIDS-collaborative/dlab-finance#19]
In the current version of `raw_taq.py`, it is [assumed that the line length is 98] (https://github.com/berkeley-dsc/dlab-finance/blob/144fcfa15b704cb192ff84b96968afc5570c9c1a/pynbbo/raw_taq.py#L42).  This seems to be correct for the most recent BBO files, including `EQY_US_ALL_BBO_20150102.zip`.  We can confirm on SAVIO with

```
zcat /global/home/users/davclark/taq-mirror/EQY_US_ALL_BBO/EQY_US_ALL_BBO_2015/EQY_US_ALL_BBO_201501/EQY_US_ALL_BBO_20150102.zip | head -n 2 | tail -n 1 | wc
```

which gives us

```
      1       4      98
```

However, I was trying the code out on the oldest BBO file we have and was having problems, even after dealing with the [absence of the record count in the first line](https://glass-bead.slack.com/archives/general/p1434653317000023).  Puzzled, I checked the line width of the file:

```
zcat /global/home/users/davclark/taq-mirror/EQY_US_ALL_BBO/EQY_US_ALL_BBO_2010/EQY_US_ALL_BBO_201001/EQY_US_ALL_BBO_20100104.zip | head -n 2 | tail -n 1 | wc
```
you get

```
      1       4      91
```

I don't have a handle on the history of the BBO file format, which is hinted at on [pp 2-3 of the Daily TAQ Client Specification](https://github.com/berkeley-dsc/dlab-finance/blob/master/docs/Daily_TAQ_Client_Spec_v2%200.pdf).

For now:  are we more interested in the most current data or the earliest data or both/neither?

**Comment by rdhyee** [comment]
Here's a modification I put to deal with differences in the first line of the BBO file: https://github.com/rdhyee/dlab-finance/commit/2566a9ac98c6682d74e5d92c781ca8148daa9ec5.

**Comment by davclark** [comment]
This is definitely something to implement in the near future. Your change looks about right. Thanks!

Could do some focused pair work next week if you're game?

**Comment by rdhyee** [comment]
I put 1-2pm on your calendar for Tuesday next week...but we could make it 2-3 hours on Tuesday afternoon.   (I'm busy late in the week with the American Library Association in SF....)  Does that work for you?

**Comment by davclark** [comment]
Don't see it on my calendar, so I'm inviting you.

On Thu, Jun 18, 2015 at 5:07 PM, Raymond Yee <notifications@github.com>
wrote:

> I put 1-2pm on your calendar for Tuesday next week...but we could make it
> 2-3 hours on Tuesday afternoon. (I'm busy late in the week with the
> American Library Association in SF....) Does that work for you?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/berkeley-dsc/dlab-finance/issues/19#issuecomment-113322851>
> .
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by davclark** [comment]
The comment for v 1.5 on page 2 of the client spec has information about this:

*12/21/2012*:
Added LULD BBO Indicator(CQS), LULD BBO Indicator (UTP), FINRA ADF MPID Indicator and SSR Indicator to the BBO file.
Added LULD NBBO Indicator(CQS) and LULD NBBO Indicator (UTP) to the NBBOfile. Changesapplicableonlytofileswitha.newsuffixuntilFebruary 1, 2013. Changes applicable to standard files from February 4, 2013.

Also for v1.8, *12/02/2013*:
Added new fields and modified existing fields, in response to Limit Up-Limit Down pilot review, to Daily Quotes, Daily Trades, Quote Admin Message and Trade Admin Message files. There's other info, including a useless link to previous specs on p. 8.

But I think we're close to everything we need. I've signed up for an account on nyx.com, so I'll be trying to progress that way.

**Comment by davclark** [comment]
OK - I got the previous version of the format in a PDF. I'll email it to folks. Note that I've made a new "copyrighted" directory under docs. I'd encourage y'all to put files there.

Leaving this open until we actually implement the code.

**Comment by rdhyee** [comment]
I computed the line width of the 2nd line in each of the BBO files: https://gist.github.com/rdhyee/8df73052c7aba1e2d89d  --> you see when the file formats start to change.  Interesting that there are .old.zip and .new.zip files along the way.
