### ISSUE TITLE
Step 1: Efficiently extract some set of securities

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/dlab-finance#7]
At this step, we can be doing a trivial computation, such as the computation of daily minimums. The structure of the TAQ data files (each security in a "clump", as I understand it) may allow us to do this efficiently without an indexed data format. Or, we may want to convert our data to a different format (e.g., parquet, HDF5).

cc @nitalpatwa

**Comment by davclark** [comment]
To be clear - the reason this is challenging is that we want to efficiently extract information from the full dataset.

Maybe it's more interesting to generate list of securities that traded <$N threshold.

**Comment by rsoni1** [comment]
Successfully computed minimums against daily file. The one next step is to use the wholeTextfile method to extract filename and with that the date into the record.

The hadoop zip example didn't work for me. Nital, can you perhaps see if you can get this to work. I will finalize and checkin the code shortly that runs on a larger dataset (month)

**Comment by nitalpatwa** [comment]
Ritesh,
At this time I am setting up a 4-node cluster in softlayer and bringing
sample data from NYSE (12G) so that
1) I can run python in interactive mode
2) Run the code on above data without getting bogged down by any cluster
issues. (but however face different set of issues)
Nital

**Comment by rsoni1** [comment]
ok. Although cluster issues have now been resolved and it's blazingly fast without any crashes like the ones we experienced earlier. You can run Spark interactively on the cluster just

export MASTER=$SPARK_URL

before starting pyspark.

**Comment by nitalpatwa** [comment]
I read about compressed files and hadoop/spark but the following questions
are unanswered:
1) zip file: Is it splittable?  i.e. can it be handled without having to
read it in entirety on one node?
I am finding that the files have a very large compression ratio, so a 6GB
file may easily overshoot the memory,
of my 16GB node on softlayer.
2) Spark talks about having hadoopFile API, and giving a compression codec:

Warning While Spark’s textFile() method can handle compressed input, it
automatically disables splittable even if the input is compressed such that
it could be read in a splittable way. If you find yourself needing to read
in a large single-file compressed input, consider skipping Spark’s wrapper
and instead use either newAPIHadoopFile or hadoopFile and specify the
correct compression codec.

But it is not clear what exactly is the API call in python.
Nital

**Comment by davclark** [comment]
There is example code already in the repository implementing the
compression codec logic!

Regarding splitting, I'm guessing it won't be a problem, but you'll need
more logic to recombine days that are split across files.

D

**Comment by nitalpatwa** [comment]
Dav,
So far I have been using only python and the interactive shell.
1) How do I build the hadoop-zip.jar?  The com-cotdp-hadoop github is there
but not sure how to deal with it.
2) Let's say that above .jar exists, how would it work with interactive
shell? Will it be similar to this?

SPARK_CLASSPATH=/path/to/elasticsearch-hadoop.jar ./bin/pyspark

Nital

**Comment by nitalpatwa** [comment]
I built the JAR with Maven, but while running in pyspark shell, ran out of
heap space.
Interestingly on the driver machine/name-node machine almost all of 16GB is
taken. Wonder who is taking it.
Nital

**Comment by nitalpatwa** [comment]
I tried rebuilding Maven with following flags (as per notes found on spark
page), but still running out heap space
when executing example. The node I have had 16GB RAM.

export MAVEN_OPTS="-Xmx4g -XX:MaxPermSize=512M
-XX:ReservedCodeCacheSize=512m"
cd com-cotdp-hadoop-master/
mvn clean package

If you are familiar with Maven, is above method of building the jar okay?

Nital

**Comment by davclark** [comment]
First of all, this is not the appropritate issue, so redirecting questions about reading zip to the issue for that: #5.
