### ISSUE TITLE
Step 3: An interesting question for Justin...

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/dlab-finance#9]
What exactly should we focus on identifying? Securities in risk of trading at <$1? Apparent high-frequency trading activity?

**Comment by davclark** [comment]
Perhaps we can do unsupervised learning - e.g., see if we can find clusters that appears to be algorithmic trading vs. human trading.

**Comment by davclark** [comment]
http://motifmap.ics.uci.edu/

It might be worth talking to Bruno: http://redwood.berkeley.edu/bruno/research/

**Comment by davclark** [comment]
Get a sense of existing approaches to identifying patterns in time series analysis from Justin?

**Comment by rsoni1** [comment]
Dav/Nital, based on the nbbo spark framework I've extended it to generate crossings where the output are tuples of stock, time in seconds, bid crossings, ask crossings. The code generates crossings for over a given threshold currently set to 10. I haven't fully benchmarked the code but given the compression in the output data generates crossings for all stocks for a given day in under 6 mins from the raw uncompressed TAQ quotes file.

Code : https://github.com/berkeley-dsc/dlab-finance/blob/master/crossings/crossings.py

Sample output
part-01232:(u'AAPL\t133841', 11, 8)
part-01232:(u'AAPL\t133844', 102, 8)
part-01232:(u'AAPL\t133845', 67, 18)
part-01232:(u'AAPL\t133846', 23, 4)
part-01232:(u'AAPL\t133850', 16, 6)
part-01232:(u'AAPL\t133851', 259, 140)
part-01232:(u'AAPL\t133852', 98, 26)
part-01232:(u'AAPL\t133853', 84, 30)
part-01232:(u'AAPL\t133854', 42, 10)
part-01232:(u'AAPL\t133855', 44, 6)
part-01232:(u'AAPL\t133856', 48, 9)
part-01232:(u'AAPL\t133858', 34, 9)
part-01232:(u'AAPL\t133859', 223, 25)
part-01232:(u'AAPL\t133900', 50, 14)
part-01232:(u'AAPL\t133901', 79, 36)
part-01232:(u'AAPL\t133902', 77, 12)
part-01232:(u'AAPL\t133903', 53, 14)
part-01232:(u'AAPL\t133906', 20, 6)

**Comment by nitalpatwa** [comment]
Ritesh, 
Cool. Really fast to do all stocks in 6 min. 
Awesome. 
Nital Patwa

**Comment by nitalpatwa** [comment]
Ritesh,
With your script, if we create a histogram of exchange code against #of
times that exchange
produces best bid or best ask nationwide, then we can find out whether
there is any exchange
that is HFT-friendly. In the flash-boys book, BATS is the one.
Also, another histogram to create is stock vs HFT event frequency, which
tells us the
favorite stocks for quote-stuffing HFTs.
Could we do that?
Thanks
Nital

**Comment by rsoni1** [comment]
Nital, Histograms would be great visualizations. I am thinking we could also use Dynamic Time Warping (DWT) as a distance measure and cluster these stocks using hierarchical clustering. http://www.rdatamining.com/examples/time-series-clustering-classification.

Dav, any other thoughts?

**Comment by davclark** [comment]
I'd be very interested to see what you get with dynamic time warping. Is this going to be easy to implement with Spark (or can you just do it with a "small data" system with some extracts you pull out with Spark)?

I'd also be very interested in looking at frequency-side patters. So, you could do something like a windowed FFT or wavelet transform of the data and see if you can identify patterns there. I don't know how comfortable you are with such techniques, or if this would be prohibitive (in terms of complexity) with Spark, but essentially, you'd end up with a set of discreet frequency bands, which you'd just treat as novel features.

**Comment by rsoni1** [comment]
I have taken the extract and analyzing in R. Here is for example a couple of the more active (high number of crossings) stocks for the single day that we processed

### Yahoo
![image](https://cloud.githubusercontent.com/assets/8722919/7334892/2fb729ea-eb6f-11e4-8c6a-997408f745b5.png)

### SPDR S&P 500 ETF Trust
![image](https://cloud.githubusercontent.com/assets/8722919/7334898/8233f9a0-eb6f-11e4-8a18-d56527336497.png)

### Sample of tickers & timestamps with Bid crossings > 3000 per sec (3rd column)
YHOO  15:02:25 3440 2728 2015-04-25 15:02:25
SPY  09:32:00 9254 4304 2015-04-25 09:32:00
EEM  14:42:07 3115  758 2015-04-25 14:42:07
IWM  15:56:41 5700 3084 2015-04-25 15:56:41

**Comment by davclark** [comment]
If you've moved to R for some of this, I might suggest we start using
Rmarkdown to organize some of this into a narrative. Have you used that
before? It's very easy with RStudio (and I'd be happy to get you started).

D

On Sat, Apr 25, 2015 at 2:28 PM, Ritesh Soni <notifications@github.com>
wrote:

> I have taken the extract and analyzing in R. Here is for example a couple
> of the more active (high number of crossings) stocks for the single day
> that we processed
> Yahoo
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/8722919/7334892/2fb729ea-eb6f-11e4-8c6a-997408f745b5.png>
> SPDR S&P 500 ETF Trust
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/8722919/7334898/8233f9a0-eb6f-11e4-8a18-d56527336497.png>
> Sample of tickers & timestamps with Bid crossings > 3000 per sec (3rd
> column)
>
> YHOO 15:02:25 3440 2728 2015-04-25 15:02:25
> SPY 09:32:00 9254 4304 2015-04-25 09:32:00
> EEM 14:42:07 3115 758 2015-04-25 14:42:07
> IWM 15:56:41 5700 3084 2015-04-25 15:56:41
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/berkeley-dsc/dlab-finance/issues/9#issuecomment-96281196>
> .
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408
